name: botcreators

services:
  telegram-bot:
    container_name: botcreators-telegram-bot
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    environment:
      DEBUG: ${DEBUG:-False}
    restart: unless-stopped
